controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: back_
    prefix: /admin/

controller_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controller_mail:
    resource: ../src/Controller/MailerController.php
    type: attribute

controller_reset_password:
    resource: ../src/Controller/ResetPasswordController.php
    type: attribute

controller_registration:
    resource: ../src/Controller/RegistrationController.php
    type: attribute